import Vue from 'vue';
import Page from '~/components/Page';
import Interior from '~/components/Interior';
import HomepageHero from '~/components/HomepageHero';
import FeaturedArtist from '~/components/FeaturedArtist';
import CompanyValues from '~/components/CompanyValues';
import ArtistGrid from '~/components/ArtistGrid';
import ArtistIntro from '~/components/ArtistIntro';
import ArtistGallery from '~/components/ArtistGallery';
import QuestionsAnswers from '~/components/QuestionsAnswers';
import List from '~/components/List';

Vue.component('Page', Page);
Vue.component('Interior', Interior);
Vue.component('HomepageHero', HomepageHero);
Vue.component('FeaturedArtist', FeaturedArtist);
Vue.component('CompanyValues', CompanyValues);
Vue.component('ArtistGrid', ArtistGrid);
Vue.component('ArtistIntro', ArtistIntro);
Vue.component('ArtistGallery', ArtistGallery);
Vue.component('QuestionsAnswers', QuestionsAnswers);
Vue.component('List', List);
